# Generated by Django 2.2.1 on 2019-06-26 13:18

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分类名')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('display', models.BooleanField(db_index=True, default=True, verbose_name='显示')),
                ('sort', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('type', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], db_index=True, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='脚本名称')),
                ('markdown', models.BooleanField(default=True, editable=False, verbose_name='markdown格式')),
                ('hits', models.IntegerField(default=0, editable=False, verbose_name='点击量')),
                ('content', mdeditor.fields.MDTextField(verbose_name='脚本内容')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('top', models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='置顶')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category', verbose_name='脚本分类')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.User', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本管理',
            },
        ),
    ]
