# Generated by Django 2.2.1 on 2019-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('type', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], db_index=True, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
